### PR TITLE
Feature/readme

### PR DESCRIPTION
**Pull request by tdubs42**
## Authors
- Tawnya Wessar
- Ben Clowe
- Jackson Reber
- Jeremy Hebert
- Dan Ferber
- Andrew Schaer
- Jake Harris
- Cara Locke

## Description

Removed template boilerplate and added HRF logo, added API Documentation section with placeholders, and styled README

## Loom Video
https://www.loom.com/share/23d20e92ecbe488986157df89f6958d3

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by tdubs42** [comment]
[Update BE README](https://trello.com/c/ZOkNHJDk/41-update-be-readme)

**Review by theawesomejaik — APPROVED** [review]
Great job team. It's coming together nicely.

**Comment by caralocke** [comment]
Looks awesome, but is showing conflicts. Once we get those situated I think it'll be great!

**Review by BradfordMez — APPROVED** [review]
ReadMe looks great so far! Appreciate all the hard work from y'alls team!

**Review by Daos21912 — APPROVED** [review]
I like the new look, good work.

**Review by crayburn18 — APPROVED** [review]
looks good so far

**Review by makeityourself121 — APPROVED** [review]
The readme is looking good but somehow your checks are failing, check on that issue.

**Review by RimshaSaleem — APPROVED** [review]

**Review by crayburn18 — APPROVED** [review]
good work!

**Review by paulstgermain — APPROVED** [review]
## Video Walkthrough Review

Another exemplary PR walkthrough from this team - you all are on a ball! Even though you all mainly made changes to the README which a lot of other people would skimp over as being a minor change not worthy of documentation, you went through each section in detail, even touching on technicalities such as changes to the `.gitignore` for your local repo and your recent noticing that auto-formatting may not be the way to go for this repo. Great stuff here!


## Code Review

Self-explanatory README changes taken up a notch! The changes made here are sensible, thorough, and well laid out, removing unnecessary details and adding those fine touches such as backlinks to HRF's own website for context.

Awesome work here overall, and an example of how our PRs should be carried out moving forward!

**Pull request merged**
