### PR TITLE
Updated npm scripts in readMe to reflect in package.json

### PR DESCRIPTION
**Pull request by juliane1999**
## Co-Authors
Juliane Vo Nguyen
Tawnya Wessar

## Description
We updated the BE README to match with the package.json in order to reduce redundancy and improve accuracy.

## Loom Video
https://www.loom.com/share/b31e5a90023a4b62b00a28822da606b9
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by tdubs42** [comment]
Oops. Prematurely made this PR. Juliane will be adding description and Loom video

**Comment by tdubs42** [comment]
[Update BE README npm scripts](https://trello.com/c/maHY8rFP/76-update-be-readme-npm-scripts)

**Review by rishimaru23 — APPROVED** [review]
great job jv!!

**Review by fervelgo — APPROVED** [review]
Clear, brief and concise! Like the rest of our readme :)
Love the clarifications.

**Pull request merged**
