### PR TITLE
Bug/sonarcloud

### PR DESCRIPTION
**Pull request by BradfordMez**
## Authors:
- Bradford Meziere
- Connor Rayburn

## Loom Video:
https://www.loom.com/share/c38e9c0981a840f79b09815e490fd8a3

Fixed Sonarcloud Scan issue with github

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by makeityourself121 — APPROVED** [review]
Good job fixing the GitHub tests.

**Comment by tdubs42** [comment]
[Why isn't our BE repo passing the tests on Github? How do we need to proceed to fix that and get those tests passing?](https://trello.com/c/ljeTd176/57-why-isnt-our-be-repo-passing-the-tests-on-github-how-do-we-need-to-proceed-to-fix-that-and-get-those-tests-passing)

**Review by RimshaSaleem — APPROVED** [review]

**Review by tdubs42 — DISMISSED** [review]
Please turn off auto formatting, `git pull origin main` and redo these changes so that the README file is not affected, nor looped into this PR.

**Comment by tdubs42** [comment]
If you need any assistance with what I requested do not hesitate to reach out

**Pull request merged**
